modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Kotori316/QuarryPlus/issues"
license="GNU Lesser General Public License v3.0"
[[mods]] 
modId="quarryplus"
version="${file.jarVersion}"
displayName="QuarryPlus"
updateJSONURL="https://raw.githubusercontent.com/Kotori316/QuarryPlus/1.17/update.json"
displayURL="https://github.com/Kotori316/QuarryPlus"
credits="Kotori316"
authors="Kotori316"
description='''
Adds some machines to make a big hole in your world.'''
[[dependencies.quarryplus]]
    modId="forge" 
    mandatory=true 
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quarryplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, )"
    ordering="NONE"
    side="BOTH"
