modLoader = "kotori_scala"
loaderVersion = "[3.3.1, ),[1,)"
issueTrackerURL = "https://github.com/Kotori316/QuarryPlus/issues"
license = "GNU Lesser General Public License v3.0"
[[mods]]
modId = "quarryplus"
version = "${file.jarVersion}"
displayName = "QuarryPlus"
updateJSONURL = "https://version.kotori316.com/get-version/1.20.4/neoforge/quarryplus"
displayURL = "https://github.com/Kotori316/QuarryPlus"
credits = "Kotori316"
authors = "Kotori316"
logoFile = "assets/quarryplus/textures/block/mod_quarryplus.png"
description = '''
Adds some machines to make a big hole in your world.'''
[[dependencies.quarryplus]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.0-beta,)"
ordering = "NONE"
side = "BOTH"
