name: Java CI Cross Check

on:
  push:
    branches:
      - "1.16"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.8, 11 ]
        # List of forge I want to check the source compiles successfully.
        forge: [ 1.16.4-35.1.4 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle16-${{ hashFiles('**/forge_version.properties') }}
      - name: download_assets
        run: |
          chmod +x ./gradlew
          ./gradlew downloadAssets || ./gradlew downloadAssets || (sleep 30s && ./gradlew downloadAssets)
        continue-on-error: true
      - id: check-parameter
        run: chmod +x ./gradlew && ./gradlew CCO --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - name: Test with JUnit
        run: chmod +x ./gradlew && ./gradlew assemble test --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ matrix.java }}-${{ matrix.forge }}
      - name: Test with runData
        run: chmod +x ./gradlew && ./gradlew -Dfml.earlyprogresswindow=false runData --info --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          CI_FORGE: ${{ matrix.forge }}
      - id: check-test-started
        run: |
          [ -f test_started.txt ]
      - id: check-error
        run: |
          ! [ -f error-trace.txt ]
      - id: show-failure-log
        if: failure()
        run: cat error-trace.txt
