name: Danger
on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Switch branch
        run: git checkout ${{ github.head_ref }}
      - name: Track all branch in remote
        run: |
          git branch -r |\
          grep -v '\->' |\
          grep -v "[^/]\+/$(git rev-parse --abbrev-ref HEAD)$" |\
          grep -v "pull/[0-9]\+/merge" |\
          sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" |\
          while read remote; do git branch --track "${remote#origin/}" "$remote"; done
      - run: git fetch --all
      - run: git show-branch | head -n 50
      - name: Get the base of checkout
        run: |
          star_index=$(git show-branch --topo-order |\
                       grep -m 1 "\[$(git rev-parse --abbrev-ref HEAD)\]" |\
                       awk '{ print index($0, "*") }')
          a="$(git show-branch --topo-order |\
               sed -n '/^--\+/,$p' |\
               tail -n +2 |\
               grep -v "\[$(git rev-parse --abbrev-ref HEAD)[0-9\^\~]\]" |\
               awk -v "q=${star_index}" '{ if(substr($0, q, 1) != " ") { print($0) } }' |\
               head -1 | \
               awk -F'[]~^[]' '{print $2}')"
          echo "BASE_BRANCH=$a" >> $GITHUB_ENV
          echo "$a"
      - name: Install danger
        run: gem install danger
      - name: Check skip
        run: |
          comment=$(gh pr view ${{ github.event.pull_request.html_url }} --json comments --jq ."comments".[]."body")
          echo "$comment" | grep -q -i "disable danger" && echo "DISABLE_DANGER=true" >> $GITHUB_ENV || :
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run danger
        run: danger --dangerfile=.github/Dangerfile.rb --fail-on-errors=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
