name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.17-fabric"
    tags:
      - "!*"
    paths:
      - "src/**"
      - ".github/workflows/gradle.yml"
      - "build.gradle"

jobs:
  commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Log Commit
        run: echo ${CONTEXT}
        env:
          CONTEXT: ${{ toJSON(github.event.head_commit) }}

  build:
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Dummy
        run: |
          echo "::group::IGNORE ME"
          chmod +x ./gradlew && ./gradlew tasks
          echo "::endgroup::"
      - name: Check Warning
        run: chmod +x ./gradlew && ./gradlew javaToolchains CheckCompileOption --no-daemon --warning-mode all
      - name: Compile
        run: chmod +x ./gradlew && ./gradlew assemble --no-daemon
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build curseforge --no-daemon
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
