name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.18-fabric"
    tags:
      - "!*"
    paths:
      - "src/**"
      - ".github/workflows/gradle.yml"
      - "build.gradle"

jobs:
  commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Log Commit
        env:
          COMMIT_CONTEXT: ${{ toJSON(github.event.head_commit) }}
        run: echo ${COMMIT_CONTEXT}
      - name: Show commit messages
        run: echo "${MESSAGES}"
        env:
          MESSAGES: ${{ toJSON(github.event.commits.*.message) }}
      - name: Check Publish ${{ contains(github.event.head_commit.message, '[release]') }}
        run: echo "Release ${{ contains(github.event.head_commit.message, '[release]') }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Dummy
        run: |
          echo "::group::IGNORE ME"
          chmod +x ./gradlew && ./gradlew tasks --no-daemon
          echo "::endgroup::"
      - name: Check Warning
        run: chmod +x ./gradlew && ./gradlew javaToolchains CheckCompileOption --no-daemon --warning-mode all
      - name: Test Only
        if: ${{ !contains(github.event.head_commit.message, '[release]') }}
        run: chmod +x ./gradlew && ./gradlew build --no-daemon
      - name: Test and Publish
        if: ${{ contains(github.event.head_commit.message, '[release]') }}
        run: chmod +x ./gradlew && ./gradlew build curseforge --no-daemon
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
