name: Build Check and Publish

on:
  push:
    branches:
      - "1.14.4"
      - "1.15.1"
    tags:
      - "!*"

jobs:
#   func:
#     runs-on: ubuntu-latest
#     steps:
#       - name: CI func
#         run: |
#           echo "$(ls ../)" && echo "$(ls ../ | grep h)"
#           echo "$(ls /)" > func_test.text
#           ls -m /
#           echo "grep = $(grep h func_test.text)"
#           test -e func_test.text
#           echo "Exists $?"
#           [ -f func_test.text ]
#           echo "Exists $?"
#           ! [ -f func_test.text ]
#           echo "Non Exists $?"
#           ! [ -f it.txt ]
#           echo "Non Exists $?"

  check:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.s1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - name: Test
        run: chmod +x ./gradlew && ./gradlew runData --info
        continue-on-error: true
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - id: check-error
        run: |
          ! [ -f error-trace.txt ]
      - id: show-failure-log
        if: failure()
        run: cat error-trace.txt
      - name: Compile
        run: chmod +x ./gradlew && ./gradlew build --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
