name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.21"
    tags:
      - "!*"
  pull_request:
    branches:
      - "1.21"

jobs:
  assemble:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kotori316/quarry-cache:1.21
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: chmod +x ./gradlew
      - run: ./gradlew assemble --scan
      - run: ./gradlew data checkReleaseVersion --no-parallel

  platforms:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kotori316/quarry-cache:1.21
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ common, fabric, forge, neoforge ]
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ls -al
      - name: Compile main ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:classes
      - name: Compile test ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:testClasses
      - name: Get run resources
        if: matrix.platform != 'neoforge' && matrix.platform != 'common'
        run: |
          (./gradlew downloadAssets) || \
            (sleep 5 && ./gradlew downloadAssets) || \
            (sleep 5 && ./gradlew downloadAssets) || true
      - name: JUnit ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:test
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Data ${{ matrix.platform }}
        if: matrix.platform != 'common'
        run: ./gradlew :${{ matrix.platform }}:runData
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_DATA: true
      - name: 'Data common(in NeoForge module)'
        if: matrix.platform == 'neoforge'
        run: ./gradlew :${{ matrix.platform }}:runCommonData
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_DATA: true
      - name: Check updated files
        if: false
        run: git diff --exit-code
      - name: GameTest ${{ matrix.platform }}
        if: matrix.platform != 'common'
        run: ./gradlew :${{ matrix.platform }}:runGameTestServer
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_GAME_TEST: true
      - name: Check report
        run: |
          ! test -d "${{ matrix.platform }}/game-test/crash-reports"
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ matrix.platform }}/build/reports/tests/*
            ${{ matrix.platform }}/game-test/crash-reports/*
          name: Test-Report-${{ github.run_number }}-QuarryPlus-${{ matrix.platform }}

  merge-checker:
    if: always()
    needs:
      - assemble
      - platforms
    uses: 'Kotori316/common-script/.github/workflows/merge-checker.yaml@main'
    with:
      needs: ${{ toJSON(needs) }}
