name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.19-fabric"
    tags:
      - "!*"
    paths:
      - "src/**"
      - ".github/workflows/gradle.yml"
      - "build.gradle"
  pull_request:
    branches:
      - "1.19-fabric"

jobs:
  commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Log Commit
        env:
          COMMIT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo ${COMMIT_CONTEXT} | jq
      - name: Show commit messages
        run: echo "${MESSAGES}" | jq
        env:
          MESSAGES: ${{ toJSON(github.event.commits.*.message) }}
      - name: Check Publish ${{ !contains(github.event.head_commit.message, '[skip release]') && github.event_name != 'pull_request' }}
        run: echo "Release ${{ !contains(github.event.head_commit.message, '[skip release]') && github.event_name != 'pull_request' }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Dummy
        run: |
          echo "::group::IGNORE ME"
          chmod +x ./gradlew && ./gradlew tasks --no-daemon
          echo "::endgroup::"
      - name: Check Warning
        run: chmod +x ./gradlew && ./gradlew javaToolchains CheckCompileOption --no-daemon --warning-mode all
      - name: Test Only
        if: ${{ contains(github.event.head_commit.message, '[skip release]') || github.event_name == 'pull_request'}}
        run: chmod +x ./gradlew && ./gradlew build --no-daemon
      - name: RunData
        run: ./gradlew runData
      - name: GameTest
        run: ./gradlew runGameTest
        env:
          RUN_GAME_TEST: true
      - name: Test and Publish
        if: ${{ !contains(github.event.head_commit.message, '[skip release]') && github.event_name != 'pull_request'}}
        run: chmod +x ./gradlew && ./gradlew build curseforge publish --no-daemon
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          AZURE_USER_NAME: 'Kotori316'
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
      - name: Upload Artifacts
        if: ${{ !contains(github.event.head_commit.message, '[skip release]') && github.event_name != 'pull_request'}}
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
