name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.21"
    tags:
      - "!*"
  pull_request:
    branches:
      - "1.21"

permissions:
  contents: read
  packages: read

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: 'false'
          job_summary: 'true'
          theme: 'dark'
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v5
      - run: chmod +x ./gradlew
      - run: ./gradlew assemble --scan
      - run: ./gradlew data checkReleaseVersion --no-parallel

  platforms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: common
          - platform: forge
            data: runGenDataData
            gameTest: runRunGameGameTestServer
          - platform: fabric
            data: runData
            gameTest: runGameTestServer
          - platform: neoforge
            data: runData
            gameTest: runGameTestServer
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v5
      - run: ls -al && whoami
      - name: Compile main ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:classes
      - name: Compile test ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:testClasses
      - name: JUnit ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:test
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Data ${{ matrix.platform }}
        if: matrix.platform != 'common'
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.data }}
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_DATA: true
      - name: 'Data common(in NeoForge module)'
        if: matrix.platform == 'neoforge'
        run: ./gradlew :${{ matrix.platform }}:runCommonData
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_DATA: true
      - name: Check updated files
        run: git diff
      - name: GameTest ${{ matrix.platform }}
        if: matrix.platform != 'common'
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.gameTest }}
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_GAME_TEST: true
      - name: Check report
        run: |
          ! test -d "${{ matrix.platform }}/game-test/crash-reports"
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          path: |
            ${{ matrix.platform }}/build/reports/tests/*
            ${{ matrix.platform }}/game-test/crash-reports/*
          name: Test-Report-${{ github.run_number }}-QuarryPlus-${{ matrix.platform }}

  merge-checker:
    if: always()
    needs:
      - assemble
      - platforms
    uses: 'Kotori316/common-script/.github/workflows/merge-checker.yaml@main'
    with:
      needs: ${{ toJSON(needs) }}
