name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.20-combined"
    tags:
      - "!*"
  pull_request:
    branches:
      - "1.20-combined"

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble --scan
      - run: ./gradlew checkJarSetting checkChangeLog checkReleaseVersion --no-parallel

  platforms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ forge, fabric, neoforge ]
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true
      - name: Compile main ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:classes
      - name: Compile test ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:testClasses
      - name: JUnit ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:test
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Data ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:runData
        env:
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_DATA: true
      - name: Check updated files
        run: git diff --exit-code
      - name: GameTest ${{ matrix.platform }}
        run: ./gradlew :${{ matrix.platform }}:runGameTest
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_GAME_TEST: true
      - name: Check report
        run: |
          ! test -d "${{ matrix.platform }}/game-test/crash-reports"
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ matrix.platform }}/build/reports/tests/*
            ${{ matrix.platform }}/game-test/crash-reports/*
          name: Test-Report-${{ github.run_number }}-QuarryPlus-${{ matrix.platform }}
