name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.16"
    tags:
      - "!*"
    paths:
      - "src/main/**"
      - "build.gradle"
      - ".github/workflows/gradle.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QuarryPlus repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile
        run: chmod +x ./gradlew && ./gradlew classes
      - name: download_assets
        run: chmod +x ./gradlew && (./gradlew clean downloadAssets || true)
        continue-on-error: true
      - name: Test with runData
        run: chmod +x ./gradlew && ( ./gradlew --no-daemon runData || ./gradlew --no-daemon runData)
      - id: check-test-started
        run: |
          [ -f test_started.txt ]
      - id: check-error
        run: |
          ! [ -f error-trace.txt ]
      - id: show-failure-log
        if: failure()
        run: cat error-trace.txt
      - name: Test with JUnit
        run: chmod +x ./gradlew && ./gradlew test
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build -x test
