name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.20-neo"
    tags:
      - "!*"
    paths:
      - "src/main/**"
      - "src/test/**"
      - "gradle.properties"
      - "build.gradle"
      - ".github/workflows/gradle.yml"
  pull_request:
    branches:
      - "1.20-neo"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true
      - name: Cache build files
        uses: actions/cache@v3
        with:
          key: neo-${{ runner.os }}-${{ hashFiles('gradle.properties') }}
          restore-keys: neo-${{ runner.os }}-
          path: build/neo*
      - name: Enable daemon
        run: sed -i -e 's/org.gradle.daemon=false/org.gradle.daemon=true/' gradle.properties
      - name: Compile 1
        run: ./gradlew classes
      - name: Compile 2
        run: ./gradlew testClasses
      - name: Assemble
        run: ./gradlew assemble
      - name: Test with JUnit
        run: ./gradlew test
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: GameTest
        if: false
        run: ./gradlew runGameTestServer
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: RunData
        run: ./gradlew runData
        env:
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Check report
        run: |
          ! test -d "game-test/crash-reports"
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/reports/tests/*
            game-test/crash-reports/*
          name: Test-Report-${{ github.run_number }}-QuarryPlus
