name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.20"
    tags:
      - "!*"
    paths:
      - "src/main/**"
      - "src/test/**"
      - "gradle.properties"
      - "build.gradle"
      - ".github/workflows/gradle.yml"
  pull_request:
    branches:
      - "1.20"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_UTILITY_LOG_ALL_TEST: true
      IGNORE_OTHER_MODS_IN_RUNTIME: true
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true
      - name: Compile
        run: ./gradlew assemble
      - name: Test with JUnit
        run: ./gradlew test
      - name: GameTest
        run: ./gradlew runGameTestServer
      - name: RunData
        run: ./gradlew runData
      - name: Check report
        run: |
          ! test -d "game-test/crash-reports"
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ github.run_number }}-${{ matrix.forge }}
