name: Build Check and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "1.19.2"
    tags:
      - "!*"
    paths:
      - "src/main/**"
      - "src/test/**"
      - "gradle.properties"
      - "build.gradle"
      - ".github/workflows/gradle.yml"
  pull_request:
    branches:
      - "1.19.2"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Warning
        run: chmod +x ./gradlew && ./gradlew javaToolchains --no-daemon --warning-mode all
      - name: Compile
        run: chmod +x ./gradlew && ./gradlew assemble --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Test with JUnit
        run: chmod +x ./gradlew && ./gradlew test --no-daemon
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Prepare resources
        run: |
          (./gradlew downloadMCMeta downloadAssets) || \
            (sleep 5 && ./gradlew downloadMCMeta downloadAssets) || \
            (sleep 5 && ./gradlew downloadMCMeta downloadAssets) || true
      - name: Test with runData
        run: chmod +x ./gradlew && ./gradlew runData --no-daemon
        env:
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: GameTest
        run: chmod +x ./gradlew && ./gradlew runGameTestServer --no-daemon
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          IGNORE_OTHER_MODS_IN_RUNTIME: true
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
