name: Release Forge

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      release_command: 'checkReleaseVersion assemble publishToMavenLocal curseforge modrinth githubRelease registerVersion publish --continue'
      enable_signature_check: true
      java_version: 17
      use_attestation: true
    secrets: inherit
