name: Release

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-read-only: true
      - name: JUnit
        run: ./gradlew test
      - name: Get run resources
        run: |
          (./gradlew downloadMCMeta downloadAssets writeMinecraftClasspathGameTestServer) || \
            (sleep 5 && ./gradlew downloadMCMeta downloadAssets writeMinecraftClasspathGameTestServer) || \
            (sleep 5 && ./gradlew downloadMCMeta downloadAssets writeMinecraftClasspathGameTestServer) || true
      - name: GameTest
        run: ./gradlew runGameTestServer
        env:
          TEST_UTILITY_LOG_ALL_TEST: false
          IGNORE_OTHER_MODS_IN_RUNTIME: true
          RUN_GAME_TEST: true
          DISABLE_FORGE: true
      - name: Check version
        run: ./gradlew checkReleaseVersion
        env:
          RELEASE_DEBUG: false

  release:
    needs:
      - check
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
      artifact-metadata: write
      # See https://github.com/Kotori316/common-script/blob/v2/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@cc63e8610e21a91ed102150d078b10d216e02b76' # v2.0.3
    with:
      release_command: 'checkReleaseVersion assemble publishToMavenLocal publishMods registerVersion publish --continue'
      enable_signature_check: false
      java_version: 25
      use_gradle_cache: true
    secrets: inherit
